name: Security

on:
  pull_request:
    paths:
      - go.mod
      - go.sum
      - package.json
      - package-lock.json
      - Dockerfile
      - "**/*.sh"
      - compose.yaml
      - .trivyignore
      - .github/workflows/security.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
    uses: cplieger/ci/.github/workflows/security-scan.yaml@a2bb34b8801329a5c0a05b4ba489a006bfb0b8d2 # v2
